#! /bin/sh

exec 0<$(dirname $0)/../../../packaging/debian/globus-connect-server/debian/source/include-binaries

mkdir -p prereqs

cd prereqs
while read package; do
    name=$(echo ${package%%-*} | tr A-Z a-z)
    url=$(curl -Ls https://pypi.org/simple/${name}/ | grep "$package" | cut -d'"' -f2 | cut -d'#' -f1)
    curl -LOs "$url"
done
cd $OLDPWD
